android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=true

# Termux aarch64: dung aapt2 cua Termux thay cho bản linux-x86_64 cua AGP
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
